spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: springproject
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect